# Generated by Django 6.0.5 on 2026-05-06 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('frames', 'Extração de Frames'), ('resize_image', 'Redução de Imagem'), ('resize_video', 'Redução de Vídeo')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Aguardando'), ('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20)),
                ('input_file', models.FileField(upload_to='uploads/')),
                ('output_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
