# Generated by Django 6.0.5 on 2026-05-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mediajob_frame_count_mediajob_input_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediajob',
            name='job_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mediajob',
            name='job_type',
            field=models.CharField(choices=[('frames', 'Extração de Frames'), ('resize_image', 'Redução de Imagem'), ('resize_video', 'Redução de Vídeo'), ('image_to_gif', 'Imagem para GIF'), ('video_to_gif', 'Vídeo para GIF')], max_length=20),
        ),
    ]
