# Generated by Django 6.0.5 on 2026-05-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gif_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediajob',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='mediajob',
            name='job_type',
            field=models.CharField(choices=[('frames', 'Extração de Frames'), ('resize_image', 'Redução de Imagem'), ('resize_video', 'Redução de Vídeo'), ('image_to_gif', 'Imagem para GIF'), ('video_to_gif', 'Vídeo para GIF'), ('batch_convert', 'Conversão em Lote')], max_length=20),
        ),
    ]
