# Generated by Django 6.0.5 on 2026-05-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_batch_convert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediajob',
            name='job_type',
            field=models.CharField(choices=[('frames', 'Extração de Frames'), ('resize_image', 'Redução de Imagem'), ('resize_video', 'Redução de Vídeo'), ('convert_format', 'Converter Formato de Imagem'), ('image_to_gif', 'Imagem para GIF'), ('video_to_gif', 'Vídeo para GIF'), ('batch_convert', 'Conversão em Lote')], max_length=20),
        ),
    ]
