# Generated by Django 6.0.5 on 2026-05-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_convert_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('frames', 'Extração de Frames'), ('resize_image', 'Redução de Imagem'), ('resize_video', 'Redução de Vídeo'), ('convert_format', 'Converter Formato de Imagem'), ('image_to_gif', 'Imagem para GIF'), ('video_to_gif', 'Vídeo para GIF'), ('batch_convert', 'Conversão em Lote')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Preço da Tarefa',
                'verbose_name_plural': 'Preços das Tarefas',
            },
        ),
        migrations.AddField(
            model_name='mediajob',
            name='payment_clipboard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediajob',
            name='payment_qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediajob',
            name='payment_status',
            field=models.CharField(choices=[('free', 'Grátis'), ('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='mediajob',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
